### ISSUE TITLE
Not working with HA 2025.1.0

### ISSUE THREAD

**Issue by Dehumanizer77** [slesinger/HomeAssistant-BMR#14]
The integration does not work with Home Assistant Core 2025.1.0 and the configuration check shows these errors (the same configuration showed no errors with 2024.12.3):

Configuration warnings
Platform error 'climate' from integration 'bmr_hc64' - cannot import name 'CURRENT_HVAC_COOL' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
Platform error 'sensor' from integration 'bmr_hc64' - cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by Rotif** [comment]
Ahoj, jak už psal uživatel tady https://github.com/slesinger/HomeAssistant-BMR/issues/12 první chybu jsem odstranil výměnou
`from homeassistant.components.climate.const import (
    CURRENT_HVAC_COOL,
    CURRENT_HVAC_HEAT,
    CURRENT_HVAC_IDLE,
    CURRENT_HVAC_OFF,
    HVAC_MODE_AUTO,
    HVAC_MODE_HEAT,
    HVAC_MODE_HEAT_COOL,
    HVAC_MODE_OFF,
    SUPPORT_PRESET_MODE,
    SUPPORT_TARGET_TEMPERATURE,
)
za
`from homeassistant.components.climate.const import (
    HVACAction.COOL,
    HVACAction.HEAT,
    HVACAction.IDLE,
    HVACAction.OFF,
    HVACMode.AUTO,
    HVACMode.HEAT,
    HVACMode.HEAT_COOL,
    HVACMode.OFF,
    ClimateEntityFeature.PRESET_MODE,
    ClimateEntityFeature.TARGET_TEMPERATURE,
)
U té druhé jsem zkusil vyměnit 
`from homeassistant.const import (
    ATTR_TEMPERATURE,
    CONF_PASSWORD,
    CONF_USERNAME,
    TEMP_CELSIUS,
)
za
`from homeassistant.const import (
    ATTR_TEMPERATURE,
    CONF_PASSWORD,
    CONF_USERNAME,
    UnitOfTemperature.CELSIUS,
)
ale chybu to bohužel neodstranilo.`
`

**Comment by Dehumanizer77** [comment]
aha, ja som tu issue len zbezne pozrel a myslel som ze je to nieco ine

**Comment by Rotif** [comment]
Každopádně chyba
Platform error 'sensor' from integration 'bmr_hc64' - cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
stále přetrvává.

**Comment by Dehumanizer77** [comment]
hmm nieje tu niekto kto by vedel co s tym?

**Comment by Rotif** [comment]
Na autora bych moc nespoléhal, zatím neřešil nic. Tak nevím, jestli už to sám nepoužívá, nebo jak.

**Comment by mirekha** [comment]
@slesinger by bylo vhodný říct, kdy cca by mohlo být opraveno, jestli teda vůbec...

**Comment by Rotif** [comment]
Myslím, že to Honza nepoužívá, jinak by to opravil.
Nainstaloval jsem toto:
https://github.com/chylek/HomeAssistant-BMR
a chodí bez problémů. Jen jsem předělal automatizace, protože filisofie ovládání je trochu jiná.

**Comment by Dehumanizer77** [comment]
Jj pozeral som na tento fork tiez len som nemal cas to skusat, tak ak to funguje tak super. 
Ta filozofia pri tom forku je presne taka ako mi vyhovuje, prave ze sa mi ten pristup tejto povodnej integracie od zaciatku zdal zvlastny.

**Comment by Knightey** [comment]
> Myslím, že to Honza nepoužívá, jinak by to opravil. Nainstaloval jsem toto: https://github.com/chylek/HomeAssistant-BMR a chodí bez problémů. Jen jsem předělal automatizace, protože filisofie ovládání je trochu jiná.

A umí tahle integrace i žaluzie?

**Comment by Dehumanizer77** [comment]
Tak som to teraz skusil a funguje ten fork, akurat netusim kde mi ostalo v konfiguracii co, ze mi to pise tieto warningy, netusite niekto? Vsetko mi funguje takze tam je niekde len zabudnute nieco v konfiguracii ale neviem sa dopatrat k tomu ze co :-)

![Image](https://github.com/user-attachments/assets/142a6c8a-afc0-4f00-8335-89b65ebbb723)

**Comment by jansemrad** [comment]
Nainstaloval jsem též, přístup přes climat entities se mi líbí mnohem více, ale vidím dobře, že jsme tím přišli o Low mode a Summer mód informaci? Nebo jenom blbě koukám v entitách a nevidím, jak jste na to vy?

**Comment by Dehumanizer77** [comment]
Nevidim to tam, ale ja som to v HA nikdy nepouzival takze neviem ani ci som to tam mal predtym...

**Comment by maniac1234** [comment]
> Myslím, že to Honza nepoužívá, jinak by to opravil. Nainstaloval jsem toto: https://github.com/chylek/HomeAssistant-BMR a chodí bez problémů. Jen jsem předělal automatizace, protože filisofie ovládání je trochu jiná.

Mohl byste prosím někdo napsat krátký postup, jak tam tento nový fork dostat, když používám původní plugin, nějak se mi to nedaří? Díky moc

**Comment by jansemrad** [comment]
Jen jsem z configuration.yaml odstranil původní integraci, smáznul ji z disku a přes HACS jsem nainstaloval novou (přidal repozitář do seznamu repozitářů HACS a dal stáhnout) - následně jsem přidal novou integraci vyplňuje se jen IP adresa HC64 v tvojí síti, jméno a heslo a frčelo to na první pokus.

**Comment by Rotif** [comment]
> Tak som to teraz skusil a funguje ten fork, akurat netusim kde mi ostalo v konfiguracii co, ze mi to pise tieto warningy, netusite niekto? Vsetko mi funguje takze tam je niekde len zabudnute nieco v konfiguracii ale neviem sa dopatrat k tomu ze co :-)
> 
> ![Image](https://github.com/user-attachments/assets/142a6c8a-afc0-4f00-8335-89b65ebbb723)

Odmaž původní zápisy z configutation.yaml

**Comment by Rotif** [comment]
> Nainstaloval jsem též, přístup přes climat entities se mi líbí mnohem více, ale vidím dobře, že jsme tím přišli o Low mode a Summer mód informaci? Nebo jenom blbě koukám v entitách a nevidím, jak jste na to vy?

Mod Low je pod Away, mod Summer pod "vypnuto". Zatím jsem netestoval, až na jaře :-)

**Comment by jv271** [comment]
Bohužel je Away na úrovni každého okruhu a nikoli globálně tak, jako v případě mobilní app BMR.
Není někde dostupná informace o přiřazení "do skupiny Away" v Mobile App?

**Comment by Rotif** [comment]
> dostupná informace o přiřazení "do skupiny Away" v Mobile App

Nevím, co znamená tato věta, ani nechápu, proč to píšeš sem a neotevřeš issue na stránce projektu.

**Comment by Dehumanizer77** [comment]
no, prave som chcel v tom forku otvorit issue ale vraj issues disabled :-/ nemate niekto kontakt na autora?
zistil som ze mi to sice funguje ale kazdu chvilu sa vsetky entity stanu nedostupne a za minutu zas ok :-(

![Image](https://github.com/user-attachments/assets/7e31baa3-0369-4d87-91f0-bcf4b01caf0a)

**Comment by chylek** [comment]
Zdravím vespolek. Omlouvám se za špatnou konfiguraci mého repozitáře, issues jsou už zapnuté. Ale předem upozorňuji, že jsem nepočítal s tím, že by můj fork získal jakoukoliv popularitu, takže čím víc toho zvládnete upravit sami a udělat PR, tím líp pro všechny :-)
https://github.com/chylek/HomeAssistant-BMR/issues

**Comment by chylek** [comment]
> > Myslím, že to Honza nepoužívá, jinak by to opravil. Nainstaloval jsem toto: https://github.com/chylek/HomeAssistant-BMR a chodí bez problémů. Jen jsem předělal automatizace, protože filisofie ovládání je trochu jiná.
> 
> A umí tahle integrace i žaluzie?

neumí


> Nainstaloval jsem též, přístup přes climat entities se mi líbí mnohem více, ale vidím dobře, že jsme tím přišli o Low mode a Summer mód informaci? Nebo jenom blbě koukám v entitách a nevidím, jak jste na to vy?

něco takového jsem tam zachoval, ale nikdy nevyzkoušel


> Bohužel je Away na úrovni každého okruhu a nikoli globálně tak, jako v případě mobilní app BMR. Není někde dostupná informace o přiřazení "do skupiny Away" v Mobile App?

já ani nevím jak se to vlastně chová pro ty kruhy co pak v away nejsou... ale takhle, můj cíl byl aby to celé mohl měnit HA. Mělo by stačit vytvořit si v něm skript, kde třeba všechny okruhy z horního patra dáte do away a místosti spodního patra ne...

**Comment by jv271** [comment]
> Bohužel je Away na úrovni každého okruhu a nikoli globálně tak, jako v případě mobilní app BMR. Není někde dostupná informace o přiřazení "do skupiny Away" v Mobile App?

> já ani nevím jak se to vlastně chová pro ty kruhy co pak v away nejsou... ale takhle, můj cíl byl aby to celé mohl měnit HA. Mělo by stačit vytvořit si v něm skript, kde třeba všechny okruhy z horního patra dáte do away a místosti spodního patra ne...

Problém aktuálního chování je v tom, že vylučuje využívání Mobile App, kde je právě logika "společného Away" pro daný set okruhů. (Okruhy, které jsou mimo set zůstávají nedotčeny.)
Když se zavolá Away na jeden okruh, tak jej vyjmeme/přidáme do setu. Tedy postupné "vypnutí Away" zruší definici sady okruhů pro Away a tak znemožní smysluplné ovládání přes mobilní aplikaci.

Jako workaround by bohatě postačovalo získat sadu/se okruhů pro Away a dále možnost přidávat a odebírat z tohoto seznamu.

**Comment by chylek** [comment]
> Problém aktuálního chování je v tom, že vylučuje využívání Mobile App, kde je právě logika "společného Away" pro daný set okruhů. (Okruhy, které jsou mimo set zůstávají nedotčeny.) Když se zavolá Away na jeden okruh, tak jej vyjmeme/přidáme do setu. Tedy postupné "vypnutí Away" zruší definici sady okruhů pro Away a tak znemožní smysluplné ovládání přes mobilní aplikaci.

Zatím aspoň přidán switch pro globální ovládání away a summer mode bez změny přiřazení okruhů. 
https://github.com/chylek/HomeAssistant-BMR/releases/tag/2.1.0

**Comment by jv271** [comment]
> > Problém aktuálního chování je v tom, že vylučuje využívání Mobile App, kde je právě logika "společného Away" pro daný set okruhů. (Okruhy, které jsou mimo set zůstávají nedotčeny.) Když se zavolá Away na jeden okruh, tak jej vyjmeme/přidáme do setu. Tedy postupné "vypnutí Away" zruší definici sady okruhů pro Away a tak znemožní smysluplné ovládání přes mobilní aplikaci.
> 
> Zatím aspoň přidán switch pro globální ovládání away a summer mode bez změny přiřazení okruhů. https://github.com/chylek/HomeAssistant-BMR/releases/tag/2.1.0

To je přímo skvělé. Díky!

**Comment by slesinger** [comment]
Zdravím,
opravil jsem nekompatibilitu v konstantách, takže integrace opět funguje. BMR stále používám a nemám v plánu na tom nic měnit. Omlouvám se za mizernou podporu – jsem nejhorší.

Přidání podpory pro dočasnou změnu teploty by bylo určitě užitečné, ale sám tuto funkci nevyužívám, takže plánuju pokračovat v současném systému:

**Automatický režim** podle kalendáře: okruhy 1–16
**Vlastní teplota**, kde se teplota nastavuje automatizací a okruhy 0–15 se zrcadlí do 16–31
Chápu, že tento systém nemusí vyhovovat uživatelům s více okruhy.

Vždycky jsem rád, když se najde společné řešení. @chylek, pokud by bylo možné vzít to nejlepší z obou přístupů a spojit je, budu jedině rád – obzvlášť proto, že na to teď nemám moc času.
